---
template:
  path: iam/role.yaml.j2

sceptre_user_data:
  project_code: {{project_code}}
  source_repo_url: {{source_repo_url}}
  roles:
    - name: CodePipelineRole
      assume_role_policy_document: |
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      description: IAM Role for CodePipeline
      path: /
      managed_policy_arns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforDataPipelineRole
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
        - arn:aws:iam::aws:policy/AWSCodeDeployDeployerAccess
      max_session_duration: 3600
      policies:
        - policy_name: AllowS3BucketAccess
          policy_document: |
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub "arn:${AWS::Partition}:s3:::wordpress-pipeline-${AWS::AccountId}-${AWS::Region}"
                Action:
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
        - policy_name: AllowS3Access
          policy_document: |
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub "arn:${AWS::Partition}:s3:::wordpress-pipeline-${AWS::AccountId}-${AWS::Region}/*"
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:PutObjectRetention
                  - s3:PutObjectTagging
                  - s3:PutObjectVersionAcl
                  - s3:PutObjectVersionTagging
                  - s3:DeleteObject
                  - s3:DeleteObjectTagging
                  - s3:DeleteObjectVersion
                  - s3:DeleteObjectVersionTagging
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:GetObjectTagging
                  - s3:GetObjectVersion
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
      tags:
        Project: {{ project_code }}

    - name: LambdaCustomCodePipeline
      assume_role_policy_document: |
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      description: IAM Role for Lambda to invoke CodeDeploy CreateDeployment
      max_session_duration: 3600
      managed_policy_arns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      policies:
        - policy_name: CustomPolicy
          policy_document: |
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - "*"
                Action:
                  - codepipeline:CreatePipeline
                  - codepipeline:UpdatePipeline
                  - codepipeline:GetPipeline
                  - codepipeline:DeletePipeline
                  - codepipeline:ListTagsForResource
                  - codepipeline:TagResource
                  - codepipeline:UntagResource
                  - iam:PassRole
      tags:
        Project: {{stack_group_config.project_code}}
